#!/bin/bash

echo "Executing all the shared regions and entities..............."
gnome-terminal -e "java main.RepositoryMain" -t "mainRepository"
gnome-terminal -e "java main.DepartureAirportMain" -t "mainDepartureAirport"
gnome-terminal -e "java main.DestinationAirportMain" -t "mainDestinationAirport"
gnome-terminal -e "java main.PlaneMain" -t "mainPlane"


echo "Launching hostess..."
gnome-terminal -e "java main.HostessMain" -t "mainHostess"
echo "Launching pilot..."
gnome-terminal -e "java main.PilotMain" -t "mainPilot"
echo "Launching passengers..."
gnome-terminal -e "java main.PassengerMain 0" -t "mainPassenger 0"
gnome-terminal -e "java main.PassengerMain 1" -t "mainPassenger 1"
gnome-terminal -e "java main.PassengerMain 2" -t "mainPassenger 2"
gnome-terminal -e "java main.PassengerMain 3" -t "mainPassenger 3"
gnome-terminal -e "java main.PassengerMain 4" -t "mainPassenger 4"
gnome-terminal -e "java main.PassengerMain 5" -t "mainPassenger 5"
gnome-terminal -e "java main.PassengerMain 6" -t "mainPassenger 6"
gnome-terminal -e "java main.PassengerMain 7" -t "mainPassenger 7"
gnome-terminal -e "java main.PassengerMain 8" -t "mainPassenger 8"
gnome-terminal -e "java main.PassengerMain 9" -t "mainPassenger 9"
gnome-terminal -e "java main.PassengerMain 10" -t "mainPassenger 10"
gnome-terminal -e "java main.PassengerMain 11" -t "mainPassenger 11"
gnome-terminal -e "java main.PassengerMain 12" -t "mainPassenger 12"
gnome-terminal -e "java main.PassengerMain 13" -t "mainPassenger 13"
gnome-terminal -e "java main.PassengerMain 14" -t "mainPassenger 14"
gnome-terminal -e "java main.PassengerMain 15" -t "mainPassenger 15"
gnome-terminal -e "java main.PassengerMain 16" -t "mainPassenger 16"
gnome-terminal -e "java main.PassengerMain 17" -t "mainPassenger 17"
gnome-terminal -e "java main.PassengerMain 18" -t "mainPassenger 18"
gnome-terminal -e "java main.PassengerMain 19" -t "mainPassenger 19"
gnome-terminal -e "java main.PassengerMain 20" -t "mainPassenger 20"

