package common;

/**
* Message Types
*/
public enum MessageType {
	PARKATTRANSFERGATE,
	INFORMPLANEREADYFORBOARDING,
	WAITFORALLINBOARD,
	FLYTODESTINATIONPOINT,
	ANNOUNCEARRIVAL,
	FLYTODEPARTUREPOINT,
	DSTOPPED,
	WAITFORNEXTFLIGHT,
	PREPAREFORPASSBOARDING,
	CHECKDOCUMENTS,
	WAITFORNEXTPASSENGER,
	INFORMPLANEREADYTOTAKEOFF,
	TRAVELTOAIRPORT,
	WAITINQUEUE,
	SHOWDOCUMENTS,
	BOARDTHEPLANE,
	WAITFORENDOFFLIGHT,
	LEAVETHEPLANE,
	// repository messages
	INQUEUE,
	OUTQUEUE,
	GETTOTALNUMBERPASSENGERSTRANSPORTED,
	INCPASSENGERSPLANE,
	DECPASSENGERSPLANE,
	INCTOTALNUMBERPASSENGERSTRANSPORTED,
	DECTOTALNUMBERPASSENGERSTRANSPORTED,
	SETPASSENGERSTATE,
	SETPILOTSTATE,
	SETHOSTESSSTATE,
	ISTOPPED
}
